apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-mysql-pv
  namespace: wordpress-test
  labels:
    type: local
    app: wordpress
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/wordpress-mysql-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-web-pv
  namespace: wordpress-test
  labels:
    type: local
    app: wordpress
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/wordpress-web-pv
