apiVersion: v1
kind: Service
metadata:
  name: semaphore
  labels:
    app: semaphore
spec:
  ports:
    - port: 3000
  selector:
    app: semaphore
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semaphore
  labels:
    app: semaphore
spec:
  selector:
    matchLabels:
      app: semaphore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: semaphore
    spec:
      restartPolicy: Always
      containers:
      - image: semaphoreui/semaphore:latest
        name: semaphore
        env:
        - name: SEMAPHORE_DB_DIALECT
          value: bolt
        - name: SEMAPHORE_ADMIN_PASSWORD
          value: P@ssw0rd
        - name: SEMAPHORE_ADMIN_NAME
          value: admin
        - name: SEMAPHORE_ADMIN_EMAIL
          value: admin@localhost
        - name: SEMAPHORE_ADMIN
          value: admin
        ports:
        - containerPort: 3000
          name: semaphore
        volumeMounts:
        - name: semaphore-volume
          mountPath: /var/lib/semaphore
      volumes:
      - name: semaphore-volume
        persistentVolumeClaim:
          claimName: semaphore-pvc